buildVariable: false
category:
- SERIF
familyName: Noto Serif Tangut
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifTangut.glyphspackage
